# version: '3'

volumes:
  db-volume:


services:
  app:
    build:
      context: ./docker/app
      dockerfile: Dockerfile
    volumes:
      # - "./docker/app/zzz-www.conf:/usr/local/etc/php-fpm.d/zzz-www.conf"
      - "./src:/var/www/vhosts/example.com/public_html"
      - "./php-fpm-socket:/run/php-fpm/"
    networks:
      - laravel_network

  nginx:
    ports: 
      - 80:80
    build:
      context: ./docker/nginx
      dockerfile: Dockerfile
    volumes:
      - "./src:/var/www/vhost/example.com/public_html"
      - "./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf"
      - "./php-fpm-socket:/run/php-fpm/" 
    depends_on:
      - app
      - mysql
    networks:
      - laravel_network

  mysql:
    ports:
      - 3306:3306
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      TZ: 'Asia/Tokyo'
    volumes:
      - "db-volume:/var/lib/mysql"
    networks:
      - laravel_network
  
  redis:
    ports:
      - 6379:6379
    build:
      context: ./docker/redis
      dockerfile: redis.Dockerfile
    networks:
      - laravel_network

networks:
  laravel_network:
    external: true
    