version: '3'

volumes:
  db-volume:

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile.production
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=mysql
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_DATABASE=database
      - DB_USERNAME=user
      - DB_PASSWORD=password
      - CACHE_DRIVER=redis
      - SESSION_DRIVER=redis
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - laravel_network
    depends_on:
      - mysql
      - redis

  nginx:
    ports: 
      - 80:80
    build:
      context: .
      dockerfile: ./docker/nginx/Dockerfile.production
    networks:
      - laravel_network
    depends_on:
      - app

  mysql:
    ports:
      - 3306:3306
    build:
      context: ./docker/mysql
      dockerfile: Dockerfile
    environment:
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'
    volumes:
      - "db-volume:/var/lib/mysql"
    networks:
      - laravel_network
  
  redis:
    ports:
      - 6379:6379
    build:
      context: ./docker/redis
      dockerfile: redis.Dockerfile
    networks:
      - laravel_network

networks:
  laravel_network:
    driver: bridge
