steps:
  # Build app image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-f','docker/app/Dockerfile.production',
        '-t','gcr.io/$PROJECT_ID/ecs-laravel-app:$SHORT_SHA',
        '-t','gcr.io/$PROJECT_ID/ecs-laravel-app:latest',
        '.'
      ]
    options:
      logging: CLOUD_LOGGING_ONLY

  # Push app image (both tags)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push','gcr.io/$PROJECT_ID/ecs-laravel-app:$SHORT_SHA']
    options:
      logging: CLOUD_LOGGING_ONLY

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push','gcr.io/$PROJECT_ID/ecs-laravel-app:latest']
    options:
      logging: CLOUD_LOGGING_ONLY

  # Build nginx image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-f','docker/nginx/Dockerfile.production',
        '-t','gcr.io/$PROJECT_ID/ecs-laravel-nginx:$SHORT_SHA',
        '-t','gcr.io/$PROJECT_ID/ecs-laravel-nginx:latest',
        '.'
      ]
    options:
      logging: CLOUD_LOGGING_ONLY

  # Push nginx image (both tags)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push','gcr.io/$PROJECT_ID/ecs-laravel-nginx:$SHORT_SHA']
    options:
      logging: CLOUD_LOGGING_ONLY

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push','gcr.io/$PROJECT_ID/ecs-laravel-nginx:latest']
    options:
      logging: CLOUD_LOGGING_ONLY

  # Build mysql image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      [
        'build',
        '-f','docker/mysql/Dockerfile.production',
        '-t','gcr.io/$PROJECT_ID/ecs-laravel-mysql:$SHORT_SHA',
        '-t','gcr.io/$PROJECT_ID/ecs-laravel-mysql:latest',
        '.'
      ]
    options:
      logging: CLOUD_LOGGING_ONLY

  # Push mysql image (both tags)
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push','gcr.io/$PROJECT_ID/ecs-laravel-mysql:$SHORT_SHA']
    options:
      logging: CLOUD_LOGGING_ONLY

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push','gcr.io/$PROJECT_ID/ecs-laravel-mysql:latest']
    options:
      logging: CLOUD_LOGGING_ONLY

images:
  - 'gcr.io/$PROJECT_ID/ecs-laravel-app:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/ecs-laravel-app:latest'
  - 'gcr.io/$PROJECT_ID/ecs-laravel-nginx:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/ecs-laravel-nginx:latest'
  - 'gcr.io/$PROJECT_ID/ecs-laravel-mysql:$SHORT_SHA'
  - 'gcr.io/$PROJECT_ID/ecs-laravel-mysql:latest'

# Deploy to Cloud Run (deploy nginx image)
# デプロイプレビュー中
#   - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
#     entrypoint: gcloud
#     args:
#       [
#         'run','deploy','$_SERVICE_NAME',
#         '--image','gcr.io/$PROJECT_ID/ecs-laravel-nginx:$SHORT_SHA',
#         '--platform','managed',
#         '--region','$_REGION',
#         '--allow-unauthenticated',
#         '--port','8080',
#         '--quiet'
#       ]

# substitutions:
#   _SERVICE_NAME: ecs-laravel
#   _REGION: asia-northeast1